name: 'Login to ECR'
description: 'Login to ECR, build Docker image, and push to ECR'
inputs:
  role-to-assume:
    description: 'Role to assume for AWS access'
    required: true
  aws-region:
    description: 'AWS Region where ECR is hosted'
    required: true
  ecr_repo_url:
    description: 'ECR Repository URL (e.g., <account_id>.dkr.ecr.<region>.amazonaws.com)'
    required: true
  repository_name:
    description: 'Name of the ECR repository'
    required: true
  image_tag:
    description: 'Tag for the Docker image'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image to Amazon ECR
      shell: bash
      env:
        REGISTRY: ${{ inputs.ecr_repo_url }}
        REPOSITORY: ${{ inputs.repository_name }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      run: |
        set -e
        echo "Building Docker image..."
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        echo "Pushing Docker image to ECR..."
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
