apiVersion: apps/v1
kind: Deployment
metadata:
  name: test_app
  labels:
    app: test_app
spec:
  replicas: 2  # Number of replicas/pods
  selector:
    matchLabels:
      app: test_app
  template:
    metadata:
      labels:
        app: test_app
    spec:
      containers:
      - name: nginx
        image: 585768185180.dkr.ecr.eu-central-1.amazonaws.com/test_app:PLACEHOLDER_HASH
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test_app-service
  labels:
    app: test_app
spec:
  type: LoadBalancer  
  ports:
  - port: 80          
    targetPort: 80
  selector:
    app: test_app
