name: Test Kubectl

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ["self-hosted", "Linux", "X64", "7itve"]
    permissions:
        id-token: write
        contents: read

    steps:
      - name: Download commit hash artifact
        uses: actions/download-artifact@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
            role-to-assume: arn:aws:iam::585768185180:role/github_oidc_role
            aws-region: ${{ vars.AWS_REGION }}
    
      - name: Update kubeconfig for EKS
        run: |
            echo "Updating kubeconfig for EKS..."

            aws eks update-kubeconfig --region eu-central-1 --name ${{ vars.CLUSTER_NAME }} 
            
            kubectl get nodes

